### ISSUE TITLE
请教如何解析build.gradle这种类型的文件呢

### ISSUE THREAD

**Issue by grayguest** [seecode-audit/clocwalk#5]
我看师父你写了解析maven的pom.xml的，但是现在也有不少是build.gradle的，由于build.gradle是采用gradle语言编写的，灵活性强，但造成了常规的正则匹配并不能很好提取到依赖和版本，我看网上推荐的都是./gradlew app:dependencies [--configuration implementation]
但是我实际测试发现，这条命令会下载依赖，如下图，那这样太影响识别效率了，想请问师父还有啥更好的方式或者思路吗？
![1LsN1f.png](https://s2.ax1x.com/2020/02/13/1LsN1f.png)

**Comment by MyKings** [comment]
暂时不支持，后期会列入计划中 ：)
